### ISSUE TITLE
sub page: query bar replacement failed: {{ query  }}

### ISSUE THREAD

**Issue by sebastian-philipp** [martin-bts/askbot-devel#1]

**Comment by martin-bts** [comment]
Fixed by
https://github.com/martin-bts/askbot-devel/commit/8440ee6b3263b45f2afdf901ce67b4f969dd56db
and
https://github.com/martin-bts/askbot-devel/commit/75ee2ca80a51427e23c22ab17dfd0a3bdb029fe5
