### ISSUE TITLE
Jinja2 error: var group_dropdown = new GroupDropdown({{ group_list }});

### ISSUE THREAD

**Issue by sebastian-philipp** [martin-bts/askbot-devel#70]
![Screenshot_20190626_204911](https://user-images.githubusercontent.com/2574405/60206455-e13ba200-9853-11e9-930b-1c48bb4dbac2.png)

**Comment by sebastian-philipp** [comment]
`{{ group_list }}` is not getting replaced properly

**Comment by martin-bts** [comment]
it would seem there are some variables that we do not pass to jinja. I think this has the same root cause as `{{ query }}` in https://github.com/martin-bts/askbot-devel/issues/1
