### ISSUE TITLE
admin page is not accessible. 

### ISSUE THREAD

**Issue by sebastian-philipp** [martin-bts/askbot-devel#77]
error: 

> Your user doen't have the permissions to access the admin page

**Comment by martin-bts** [comment]
Looks like you don't have the required permissions

**Comment by martin-bts** [comment]
It works for me, if I use an admin user. I had to fix the add_admin command for this, see https://github.com/martin-bts/askbot-devel/commit/e43c761dbeeddf2ad06f308732b66df441597321
